title: furyohfury Unity portfolio
description: Здесь вы можете посмотреть на прототипы(и не только) проектов, сделанных мной!
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-relative-links
show_downloads: false
safe: false
github:
  is_project_page: false
baseurl: "/PortfolioWebsite"  # Имя вашего репозитория
url: "https://furyohfury.github.io"  # Без слеша в конце
collections:
  projects:
    output: true  # Генерирует отдельные страницы
    permalink: /projects/:name/  # ЧПУ-ссылки вида /projects/game1/
  neon-what-screenshots:
    output: false
    permalink: /neon-what-screenshots/:name/
  pikmin-screenshots:
    output: false
    permalink: /pikmin-screenshots/:name/
  zero-resistance-screenshots:
    output: false
    permalink: /zero-resistance-screenshots/:name/
  card-autobattler-screenshots:
    output: false
    permalink: /card-autobattler-screenshots/:name/
  money-run-screenshots:
    output: false
    permalink: /money-run-screenshots/:name/
  taiko-screenshots:
    output: false
    permalink: /taiko-screenshots/:name/