title: My portfolio for unity
description: Simple site
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-relative-links
collections:
  projects:
    output: true  # Генерирует отдельные страницы
    permalink: /projects/:name/  # ЧПУ-ссылки вида /projects/game1/